### ISSUE TITLE
Задачи 1.3.24 .. 1.3.26

### ISSUE THREAD

**Issue by be9** [v-log/Training#13]
1. Write a method `removeAfter()` that takes a linked-list `Node` as argument and removes the node following the given one (and does nothing if the argument or the next field in the argument node is null).
2. Write a method `insertAfter()` that takes two linked-list `Node` arguments and inserts the second after the first on its list (and does nothing if either argument is null).
3. Write a method `remove()` that takes a linked list and a string `key` as arguments and removes all of the nodes in the list that have key as its item field.

**Comment by v-log** [comment]
@be9 В итераторе из книги в generic аргумент <Item> (если я правильно выразился). И оперировать Node мы через него не можем. 
Вопрос: можно изменять итератор, или это нужно другим путем как-то решить?
(например, для того, чтобы удалить какой-то Node, нам нужно иметь ссылку на него, но ее неоткуда взять просто)

**Comment by v26** [comment]
@be9 В итераторе из книги в generic аргумент `<Item>` (если я правильно выразился). И оперировать Node мы через него не можем. (например, для того, чтобы удалить какой-то Node, нам нужно иметь ссылку на него, но ее неоткуда взять просто)
Вопрос: можно изменять итератор, или это нужно другим путем как-то решить?

**Comment by v26** [comment]
@be9 Код для итератора, чтобы не искать (уже с моими коррективами, правда)

```
    private Node first; // top of stack (most recently added node)
    private int N; // number of items

    private class Node
    { // nested class to define nodes
        Item item;
        Node next;
    }

    public boolean isEmpty() { return first == null; } // Or: N == 0.

    public int size()    { return N; }

    public void push(Item item)
    { // Add item to top of stack.
        Node oldfirst = first;
        first = new Node();
        first.item = item;
        first.next = oldfirst;
        N++;
    }

    public Item pop()
    { // Remove item from top of stack.
        Item item = first.item;
        first = first.next;
        N--;
        return item;
    }

    public Iterator<Item> iterator()
    { return new ListIterator(); }

    private class ListIterator implements Iterator<Item>
    {
        private Node current = first;
        private Node realCurrent;
        private Node prev = null;

        public boolean hasNext()
        { return current != null; }

        public void remove() {
            if ( prev == null ) {
                realCurrent = null;
                first = current;
            }
            else prev.next = current;

            N--;
        }

        public Item next() {
            prev = realCurrent;
            realCurrent = current;
            Item item = current.item;
            current = current.next;
            return item;
        }
    }
```

Методы я написал:

```
public void removeAfter(Node nodeToRemoveAfter) {
        if ( nodeToRemoveAfter != null && nodeToRemoveAfter.next != null ) {
            Node nodeToRemove = nodeToRemoveAfter.next;
            nodeToRemoveAfter.next = nodeToRemove.next;
            N--;
        }
    }

    public void insertAfter(Node node1, Node nodeToIns) {
        if ( node1 != null && nodeToIns != null ) {
            Node temp = node1.next;
            node1.next = nodeToIns;
            nodeToIns.next = temp;
            N++;
        }
    }

    public void remove(LinkedListStack<Item> list, String key) {
        Iterator<Item> iter = list.iterator();

        while (iter.hasNext()) {
            Item curr = iter.next();

            if ( curr.equals(key) ) {
                iter.remove();
                N--;
            }

        }
    }
```

Но проверить их не могу, так как не могу "взять" Node, а только Item, через iterator

**Comment by be9** [comment]
Да, здесь `removeAfter` и `insertAfter` получаются внутренними методами. Проверить их можно, лишь вызывая их изнутри самого класса. Но реализовал ты их верно. 👍 

Что касается метода `remove`, то его как раз проверить можно. Идеи для тестов: удаление в пустом списке, удаление ВСЕХ элементов, удаление первого, удаление в середине, удаление последнего, удаление ни одного элемента.
