### ISSUE TITLE
Портировать алгоритм сортировки вставкой на Ruby

### ISSUE THREAD

**Issue by be9** [v-log/Training#35]
Алгоритм 2.2, стр. 251.

Аналогично ч.2 #34.

```ruby
def insertion_sort(a)
  # ...
end

a = [['Vasya', 1], ['Petya', 3], ['Kolya', 2]]
insertion_sort(a) { |item| -item[1] }
puts a.inspect # [["Petya", 3], ["Kolya", 2], ["Vasya", 1]]
```

**Comment by v26** [comment]
@be9 Насчет исключений мне непонятно: в методах нужно ограничить воспринимаемые типы аргументов, я так понимаю - для #sorted? и #insertion_sort оставить Array, а для #insertion_sort2 - Array и Hash?

#sorted? может сработать и со строкой, но нужно ли это здесь?

**Comment by be9** [comment]
Что-то я не понял вопрос. Никаких ограничений не надо.

**Comment by v26** [comment]
@be9 Ну я думал кинуть исключения, например, если не Comparable или не Enumerable (потом, правда, увидел, что String, например не Enumerable, но все равно #sorted? со строкой срабатывает, но не суть...). 
Ну а кинуть исключения, если переданный объект `empty?` ?

**Comment by be9** [comment]
Не надо этих проверок. В Ruby, как и в других динамических языках, используется принцип "duck typing" (погугли). Т.е. если нечто выглядит как уточка и крякает как уточка, неважно, наследуется оно от класса `Duck` или нет. Так и здесь: если у наших объектов объявлен метод `<=>`, то всё сработает, а откуда он взялся — пофиг.

Что касается сортировки пустого массива, то это вовсе не ошибка (лишь бы код на этом не падал).
