### ISSUE TITLE
Задачи 2.1.6, 2.1.7, 2.1.8, 2.1.10

### ISSUE THREAD

**Issue by be9** [v-log/Training#37]
- [x] **2.1.6.** Which method runs faster for an array with all keys identical, selection sort or insertion sort?
- [x] **2.1.7.** Which method runs faster for an array in reverse order, selection sort or insertion sort?
- [x] **2.1.8.** Suppose that we use insertion sort on a randomly ordered array where elements have only one of three values. Is the running time linear, quadratic, or something in between?
- [x] **2.1.10.** Why not use selection sort for _h_-sorting in shellsort?

Ответы с обоснованиями — в комментарии здесь.

**Comment by v26** [comment]
@be9 
2.1.6 При всех элементах массива одинаковых:
- selection sort сделает N перестановок каждого элемента с самим собой ( exch(a, i, min) повторится N раз )
```
int N = a.length;    // array length
for (int i = 0; i < N; i++)
{    // Exchange a[i] with smallest entry in a[i+1...N).
    int min = i;    // index of minimal entr.
    for (int j = i+1; j < N; j++)
        if (less(a[j], a[min])) min = j;
    exch(a, i, min);
}
```
- insertion sort в этом случае не совершит никакой операции во внутреннем цикле
```
int N = a.length;
for (int i = 1; i < N; i++)
{    // Insert a[i] among a[i-1], a[i-2], a[i-3]... ..
     for (int j = i; j > 0 && less(a[j], a[j-1]); j--)
         exch(a, j, j-1);
}
```
Ответ: ~N > ~1  ==> insertion sort - быстрее в этом случае.

**Comment by v26** [comment]
@be9 
2.1.7 И selection sort и insertion sort в случае обратно-отсортированного массива (worst case) производят ~N^2/2 сравнений, однако, selection sort делает ~N перестановок, а insertion sort -  ~N^2/2 перестановок. 
Также, в selection sort происходит  ~N^2/2 присваиваний min. 

Перестановка = 3 присваивания. 

Тогда, selection sort делает ~3N + N^2/2 присваиваний, в целом; insertion sort делает ~N^2 * 3/2 присваиваний.
При делении количеств присваиваний insertion sort / selection sort получаем 3N / (N+6) ~ 3.

Ответ: selection sort, в случае с обратно-сортированным массивом, быстрее, чем insertion sort, в 3 раза.

**Comment by be9** [comment]
@v-log По 2.1.6. Ответ верный. Selection sort сделает всего ~N^2 операций, а insertion ~N.

**Comment by be9** [comment]
@v-log 2.1.7 👍

**Comment by v26** [comment]
@be9 В 2.1.6 ~N^2 и ~N потому, что less() (то бишь compareTo() ) совершает одну операцию?

**Comment by v26** [comment]
@be9 2.1.8
Если представить три разных числа как x, y, z, а их количество как коэффициенты A, B, C,
то N = A + B + C.

xxxxyyyyyzzz - упорядоченный массив.

худший случай: zzzzyyyyyxxxx

z - никуда не перемещаются, т.к. z не меньше других элементов.
y - нужно "преодолеть" только z, дальше y не идет; 
тогда макс. кол-во перемещений (обменов) всех y = B * С.
x - нужно "преодолеть" y и z,
тогда макс. кол-во перемещений всех x = A * (B + C).

Получается, макс. кол-во перемещений для N элементов = A*(B + C) + B*C = A*B + A*C + B*C

Линейное кол-во перемещений N = (A + B + C)

Квадр-е N^2 = (A + B + C) * (A + B + C) = A*B + A*C + B*C  +  A^2 + B^2 + C^2 + A*B +A*C + B*C

(A + B + C)   <   A*B + A*C + B*C   <   A*B + A*C + B*C  +  A^2 + B^2 + C^2 + A*B +A*C + B*C

Ответ: running time для данного случая будет между линейным и квадратичным.

**Comment by be9** [comment]
@v-log по 2.1.6 да.

**Comment by be9** [comment]
@v-log по 2.1.8 логика в принципе верная, но давай посмотрим внимательнее.

То, что время не может быть линейным, очевидно, ибо мы раньше установили, что линейное время возникает в массиве из одинаковых элементов, где внутренний цикл вообще не работает. Здесь же всё-таки нужно тащить элементы. Поэтому весь вопрос сводится к тому, даёт ли уменьшение разнообразия элементов какое-то улучшение базового квадратичного времени или нет.

Если предположить, что A=B=C=N/3, то можно прикинуть выигрыш. AB+AC+BC=N<sup>2</sup>/3. Т.е. при равных пропорциях время в 1.5 раза меньше относительно базового худшего случая ~N<sup>2</sup>/2. В принципе, это объяснимо, потому что в среднем элемент во внутреннем цикле надо протаскивать не на половину массива, а на треть.

Короче, время остаётся квадратичным, но коэффициент меньше.

**Comment by v26** [comment]
@be9 Да, понял. Очевидно, что средний путь для каждого элемента сократится, но не догадался предположить N<sup>2</sup>/3.

**Comment by v26** [comment]
@be9 2.1.10
Предпочтительнее использовать модификацию insertion sort, а не selection sort просто потому, что последняя будет медленнее в ~N раз (как мы выяснили в 2.1.6).

**Comment by be9** [comment]
@v-log в 2.1.6 у нас был массив из одинаковых элементов. Здесь всё-таки это не так.

**Comment by v26** [comment]
@be9 В 2.1.6 - не могу понять. Математически кажется, что selection sort лучше подойдет, потому что обменов меньше буде производиться. Могу только предположить, что в процессе сортировки через shellsort образуется много частично или полностью сортированных массивов, и тогда выгоднее insertion sort?

**Comment by be9** [comment]
@v-log ты, видимо, имеешь в виду 2.1.10. Да, ответ именно таков: чем более отсортирован массив, т.е. чем ближе элементы к своим истинным местам по порядку, тем меньше операций потребуется для insertion sort, в то время как время работы selection sort слабо меняется. А поскольку shellsort доставляет нам на каждом шаге всё более и более сортированный массив, выбор insertion sort становится оправданным.

**Comment by be9** [comment]
Закрываю, вроде со всеми вопросами разобрались.

**Comment by v26** [comment]
@be9 Ой, да, 2.1.10 имел в виду
