### ISSUE TITLE
Задача 2.1.20. Shellsort best case

### ISSUE THREAD

**Issue by be9** [v-log/Training#39]
What is the best case for shellsort? Justify your answer.

Ответ — в комментарии.

**Comment by v26** [comment]
@be9 
Здесь то же, что и в предыдущих алгоритмах сортировки, лучший случай - все элементы одинаковые, чтобы exch() не был вызван ни разу.
```
for (int i = h; i < N; i++)
{    // Insert a[i] among a[i-h], a[i-2*h], a[i-3*h]... .
    for (int j = i; j >= h && less(a[j], a[j-h]); j -= h)
        exch(a, j, j-h);
}
```

**Comment by be9** [comment]
Верно!
