### ISSUE TITLE
Задача 2.2.22. 3-way mergesort

### ISSUE THREAD

**Issue by be9** [v-log/Training#49]
Suppose instead of dividing in half at each step, you divide into thirds, sort each third, and combine using a 3-way merge. What is the order of growth of the overall running time of this algorithm?

(здесь нужен просто ответ)

**Comment by v26** [comment]
@be9  Решение по аналогии с Proof of Proposition F (Ch.2, p.272 - 274), C(N) =Nlog3N (имеется в виду по основанию 3).

**Comment by be9** [comment]
Да, типа того.

**Comment by v26** [comment]
@be9 Наверное, я написал непонятно - имел в виду N умножить на логарифм N по основанию 3. Так верно?

**Comment by be9** [comment]
Ну я так и понял :)
